# Generated by Django 6.0.6 on 2026-06-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=20, verbose_name='統一編號')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='業者名稱')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='業別')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('registered_at', models.DateField(blank=True, null=True, verbose_name='登錄日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '食品業者',
                'verbose_name_plural': '食品業者',
            },
        ),
    ]
